# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main   
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # VPS IP
          host: ${{ secrets.SSH_HOST }}
          # VPS username
          username: ${{ secrets.SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          #key: #${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}
          # passphrase
          password: ${{ secrets.SSH_PASSPHRASE }}
          script: |  
            cd ${{ secrets.PROJECT_PATH }}
            git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
            git pull origin main 
            make down
            make build
            make show_logs
            echo "Deleting old image(s)..."
            docker image prune -a -f